### ISSUE TITLE
win下部署小真寻无法使用 

### ISSUE THREAD

**Issue by quanquan1014** [NumberSir/zhenxun_arktools#1]
![image](https://user-images.githubusercontent.com/69108232/171587426-179c1550-a31c-4ae8-af0d-cb89f8ad284f.png)
<img width="327" alt="image" src="https://user-images.githubusercontent.com/69108232/171587448-c221bb33-5355-4f78-b994-8534662d5b06.png">
<img width="396" alt="image" src="https://user-images.githubusercontent.com/69108232/171587482-643c32b1-3ceb-49d7-b999-1046a7046ce5.png">

**Comment by aillear** [comment]
> ![image](https://user-images.githubusercontent.com/69108232/171587426-179c1550-a31c-4ae8-af0d-cb89f8ad284f.png) <img alt="image" width="327" src="https://user-images.githubusercontent.com/69108232/171587448-c221bb33-5355-4f78-b994-8534662d5b06.png"> <img alt="image" width="396" src="https://user-images.githubusercontent.com/69108232/171587482-643c32b1-3ceb-49d7-b999-1046a7046ce5.png">

我ubuntu也是一样,估计是网络问题把

**Comment by NumberSir** [comment]
> ![image](https://user-images.githubusercontent.com/69108232/171587426-179c1550-a31c-4ae8-af0d-cb89f8ad284f.png) <img alt="image" width="327" src="https://user-images.githubusercontent.com/69108232/171587448-c221bb33-5355-4f78-b994-8534662d5b06.png"> <img alt="image" width="396" src="https://user-images.githubusercontent.com/69108232/171587482-643c32b1-3ceb-49d7-b999-1046a7046ce5.png">



> > ![image](https://user-images.githubusercontent.com/69108232/171587426-179c1550-a31c-4ae8-af0d-cb89f8ad284f.png) <img alt="image" width="327" src="https://user-images.githubusercontent.com/69108232/171587448-c221bb33-5355-4f78-b994-8534662d5b06.png"> <img alt="image" width="396" src="https://user-images.githubusercontent.com/69108232/171587482-643c32b1-3ceb-49d7-b999-1046a7046ce5.png">
> 
> 我ubuntu也是一样,估计是网络问题把

这个是请求 https://prts.wiki/ 网页超时了，我晚些时间重新改一下实现

**Comment by quanquan1014** [comment]
<img width="910" alt="image" src="https://user-images.githubusercontent.com/69108232/172015634-cc555c98-27e1-4312-b390-5d347bde6656.png">

**Comment by quanquan1014** [comment]
@NumberSir 依旧超时 (•̩̩̩̩＿•̩̩̩̩)

**Comment by a930389426** [comment]
截图失败可以试着修改源代码里获取截图的超时时间，我将10000ms改成了50000ms就成功了，我windows系统

**Comment by quanquan1014** [comment]
> 截图失败可以试着修改源代码里获取截图的超时时间，我将10000ms改成了50000ms就成功了，我windows系统

感谢已解决
