### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by PackageInstaller** [NumberSir/zhenxun_arktools#11]
![image](https://user-images.githubusercontent.com/80018096/222201638-6e740092-7a16-44a7-8f1c-6ece21cd5004.png)

![image](https://user-images.githubusercontent.com/80018096/222201589-9ca56882-c057-49fd-affa-30826b276624.png)

**Comment by NumberSir** [comment]
库名叫 `tortoise-orm` 不叫 `tortoise`。
`pip install tortoise-orm`
