### ISSUE TITLE
公开招募功能导入失败怎么搞

### ISSUE THREAD

**Issue by a930389426** [NumberSir/zhenxun_arktools#2]
![QQ截图20220607175055](https://user-images.githubusercontent.com/59648220/172351558-222a57c7-4231-4a39-b1d6-a29d6a5114d1.png)
报错如图所示

**Comment by NumberSir** [comment]
> ![QQ截图20220607175055](https://user-images.githubusercontent.com/59648220/172351558-222a57c7-4231-4a39-b1d6-a29d6a5114d1.png) 报错如图所示

修复了，请重新下载。我之前用了py3.9以上才支持的类型注释
