### ISSUE TITLE
公开招募含有"术师"TAG时无法正确计算

### ISSUE THREAD

**Issue by YRFBK** [NumberSir/zhenxun_arktools#3]
如题 操作系统 winserver2012;Python 3.9.13 ;zhenxun_bot v0.1.6.1

![1)4IJGGG)VG$XJSAE)`8_0W](https://user-images.githubusercontent.com/72265872/180018931-d615848e-cba2-4c82-bebf-92e2a9471c0c.png)

![image](https://user-images.githubusercontent.com/72265872/180019071-ea419b45-9e55-486b-971c-1b910d1058af.png)

**Comment by NumberSir** [comment]
> 如题 操作系统 winserver2012;Python 3.9.13 ;zhenxun_bot v0.1.6.1
> 
> ![1)4IJGGG)VG$XJSAE)`8_0W](https://user-images.githubusercontent.com/72265872/180018931-d615848e-cba2-4c82-bebf-92e2a9471c0c.png)
> 
> ![image](https://user-images.githubusercontent.com/72265872/180019071-ea419b45-9e55-486b-971c-1b910d1058af.png)

是接口 api 问题，已修复，请重新下载安装。

**Comment by YRFBK** [comment]
![uTools_1658888641902](https://user-images.githubusercontent.com/72265872/181146933-3c17a248-be38-4ce3-af02-d80ed2af9862.png)
发现仍存在与"术师"tag有关的计算问题：现在不会因为含有"术师"tag而直接无法计算，但仍无法计算出有"术师"tag的稀有干员。如图上的术师+减速(格雷伊)，术师+治疗(夜魔)。
