### ISSUE TITLE
加载插件异常

### ISSUE THREAD

**Issue by MobiusT** [NumberSir/zhenxun_arktools#6]
系统 debain11
加载插件时报如下异常
![5L~I)8XZ8EKHWS3B3MVF(4S](https://user-images.githubusercontent.com/62053271/201486947-76226630-5b1b-4cbb-b7c9-c3859b867ced.png)
![JPC($QU@JPJ7PB W N}CO1R](https://user-images.githubusercontent.com/62053271/201486950-1d420ee1-a447-4d28-a37e-ffa050f905ec.png)
使用的是直接clone本仓库后获取的文件夹

**Comment by moshuiNW** [comment]
我也有同样的问题系统 ubuntu20.04用的是Release v1.0.0
![QQ截图20221113155023](https://user-images.githubusercontent.com/110805397/201511763-d66a5d73-275e-4bef-a4e3-73bc82673cf8.png)
![QQ截图20221113155419](https://user-images.githubusercontent.com/110805397/201511771-a4514b68-ed4f-4bdb-a6c1-8d27e165169d.png)

**Comment by MobiusT** [comment]
[rc1](https://github.com/nonebot/nonebot2/releases/tag/v2.0.0-rc.1)
将nb2版本升级到rc1后可以正常加载，需注意rc1有破坏性变更，可能导致其他插件报错
