### ISSUE TITLE
加载插件异常

### ISSUE THREAD

**Issue by moshuiNW** [NumberSir/zhenxun_arktools#7]
这是什么原因啊？ubuntu20.04 python3.9.15 nb2版本rc1 一载入就报错这两个错删掉插件后无报错 是不是少了什么东西？
poetry install也显示"No dependencies to install or update" 为什么会报错呢？
![1](https://user-images.githubusercontent.com/110805397/201516840-2f84a02a-f42b-4c72-84bb-405476f01358.png)
![2](https://user-images.githubusercontent.com/110805397/201516842-06ca806c-37c2-4e81-bf85-8a3ac64c4f6c.png)

**Comment by hutu0913** [comment]
佬，怎么解决的，我也遇到了

**Comment by niucattle** [comment]
> 佬，怎么解决的，我也遇到了

pip install --upgrade tencentcloud-sdk-python -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com --trusted-host pypi.douban.com
