### ISSUE TITLE
tool_announce_push | checking rss news... 导致消息阻塞

### ISSUE THREAD

**Issue by Nenot233** [NumberSir/zhenxun_arktools#9]
02-16 20:39:21 [INFO] tool_announce_push | checking rss news...
执行之后导致消息阻塞（表现为卡顿，无法及时处理其他信息）

**Comment by NumberSir** [comment]
> 02-16 20:39:21 [INFO] tool_announce_push | checking rss news... 执行之后导致消息阻塞（表现为卡顿，无法及时处理其他信息）

已添加关闭自动检测公告更新的配置项，请重新下载
